In [62]:
import numpy as np

In [63]:
myarr = np.array([[3,6,32,7],])

In [64]:
myarr[0,1]

np.int64(6)

In [65]:
myarr.shape

(1, 4)

In [66]:
myarr.dtype

dtype('int64')

In [67]:
myarr[0,1] = 45

In [68]:
myarr

array([[ 3, 45, 32,  7]])

In [69]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [70]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [71]:
listarray.dtype

dtype('int64')

In [72]:
listarray.shape

(3, 3)

In [73]:
listarray.size

9

In [74]:
np.array({32:5 , 44:6})

array({32: 5, 44: 6}, dtype=object)

In [75]:
zeros = np.zeros((3,3))

In [76]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
rng = np.arange(1,15)

In [78]:
rng

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [100]:
Lspace = np.linspace(1,4,4)

In [101]:
Lspace

array([1., 2., 3., 4.])

In [102]:
emp = np.empty((4,6))

In [103]:
emp

array([[2.22809558e-312, 2.46151512e-312, 2.41907520e-312,
        2.05833592e-312, 9.76118064e-313, 2.46151512e-312],
       [2.37663529e-312, 2.12199580e-313, 2.22809558e-312,
        2.46151512e-312, 2.41907520e-312, 2.05833592e-312],
       [9.76118064e-313, 2.20687562e-312, 2.37663529e-312,
        2.12199580e-313, 2.22809558e-312, 2.46151512e-312],
       [2.41907520e-312, 2.05833592e-312, 9.76118064e-313,
        2.22809558e-312, 2.14321575e-312, 2.56765117e-312]])

In [104]:
empLike = np.empty_like(Lspace)

In [105]:
empLike

array([1., 2., 3., 4.])

In [108]:
ide = np.identity(3)

In [109]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [110]:
arr = np.arange(99)

In [111]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [116]:
arr= arr.reshape(3,33)

In [117]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [119]:
arr = arr.ravel()

In [120]:
arr.shape

(99,)

In [121]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [122]:
ar = np.array(x)

In [123]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [124]:
ar.sum(axis=0)

array([12,  8,  9])

In [125]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [127]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [128]:
ar.flat

In [129]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [130]:
ar.ndim

2

In [131]:
ar.size

9

In [132]:
ar.nbytes

72

In [141]:
one = np.array([1,2,3,456,5])

In [136]:
one.argmax()

np.int64(3)

In [137]:
one[one.argmax()]

np.int64(456)

In [138]:
one[one.argmin()]

np.int64(1)

In [139]:
one.argsort()

array([0, 1, 4, 2, 3])

In [142]:
one[one.argsort()]

array([  1,   2,   3,   5, 456])

In [143]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [147]:
ar.argmin()

np.int64(8)

In [151]:
ar.argmax(axis=1)

array([2, 2, 0])

In [153]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [154]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [156]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [158]:
ar2 = np.array(([[1,2,1],
       [4, 0, 6],
       [8,1,0]]))

In [159]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [162]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [163]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [164]:
ar.sum()

np.int64(29)

In [169]:
ar.min()

np.int64(0)

In [170]:
ar.max()

np.int64(7)

In [171]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [172]:
np.count_nonzero(ar)

np.int64(8)

In [173]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [174]:
ar[1,2] = 0

In [175]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [181]:
import sys

In [176]:
pyar = [0,4,45,2] 

In [179]:
npar = np.array(pyar)

In [182]:
sys.getsizeof(1) * len(pyar)

112

In [183]:
npar.itemsize * npar.size

32